// Code generated by "stringer -type Command"; DO NOT EDIT

package dexcom

import "fmt"

const (
	_Command_name_0 = "NULLACKNAKINVALID_COMMANDINVALID_PARAMINCOMPLETE_PACKET_RECEIVEDRECEIVER_ERRORINVALID_MODE"
	_Command_name_1 = "PINGREAD_FIRMWARE_HEADER"
	_Command_name_2 = "READ_DATABASE_PARTITION_INFOREAD_DATABASE_PAGE_RANGEREAD_DATABASE_PAGESREAD_DATABASE_PAGE_HEADER"
	_Command_name_3 = "READ_TRANSMITTER_IDWRITE_TRANSMITTER_IDREAD_LANGUAGEWRITE_LANGUAGEREAD_DISPLAY_TIME_OFFSETWRITE_DISPLAY_TIME_OFFSETREAD_RTCRESET_RECEIVERREAD_BATTERY_LEVELREAD_SYSTEM_TIMEREAD_SYSTEM_TIME_OFFSETWRITE_SYSTEM_TIMEREAD_GLUCOSE_UNITWRITE_GLUCOSE_UNITREAD_BLINDED_MODEWRITE_BLINDED_MODEREAD_CLOCK_MODEWRITE_CLOCK_MODEREAD_DEVICE_MODE"
	_Command_name_4 = "ERASE_DATABASESHUTDOWN_RECEIVERWRITE_PC_PARAMETERSREAD_BATTERY_STATEREAD_HARDWARE_BOARD_ID"
	_Command_name_5 = "READ_FIRMWARE_SETTINGSREAD_ENABLE_SETUP_WIZARD_FLAG"
	_Command_name_6 = "READ_SETUP_WIZARD_STATE"
	_Command_name_7 = "READ_CHARGER_CURRENT_SETTINGWRITE_CHARGER_CURRENT_SETTING"
)

var (
	_Command_index_0 = [...]uint8{0, 4, 7, 10, 25, 38, 64, 78, 90}
	_Command_index_1 = [...]uint8{0, 4, 24}
	_Command_index_2 = [...]uint8{0, 28, 52, 71, 96}
	_Command_index_3 = [...]uint16{0, 19, 39, 52, 66, 90, 115, 123, 137, 155, 171, 194, 211, 228, 246, 263, 281, 296, 312, 328}
	_Command_index_4 = [...]uint8{0, 14, 31, 50, 68, 90}
	_Command_index_5 = [...]uint8{0, 22, 51}
	_Command_index_6 = [...]uint8{0, 23}
	_Command_index_7 = [...]uint8{0, 28, 57}
)

func (i Command) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _Command_name_0[_Command_index_0[i]:_Command_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _Command_name_1[_Command_index_1[i]:_Command_index_1[i+1]]
	case 15 <= i && i <= 18:
		i -= 15
		return _Command_name_2[_Command_index_2[i]:_Command_index_2[i+1]]
	case 25 <= i && i <= 43:
		i -= 25
		return _Command_name_3[_Command_index_3[i]:_Command_index_3[i+1]]
	case 45 <= i && i <= 49:
		i -= 45
		return _Command_name_4[_Command_index_4[i]:_Command_index_4[i+1]]
	case 54 <= i && i <= 55:
		i -= 54
		return _Command_name_5[_Command_index_5[i]:_Command_index_5[i+1]]
	case i == 57:
		return _Command_name_6
	case 59 <= i && i <= 60:
		i -= 59
		return _Command_name_7[_Command_index_7[i]:_Command_index_7[i+1]]
	default:
		return fmt.Sprintf("Command(%d)", i)
	}
}
