// Code generated by "stringer -type PageType"; DO NOT EDIT.

package dexcom

import "fmt"

const (
	_PageType_name_0 = "ManufacturingDataFirmwareDataSoftwareDataSensorDataEGVDataCalibrationDataDeviationDataInsertionTimeDataReceiverLogDataReceiverErrorDataMeterDataUserEventDataUserSettingData"
	_PageType_name_1 = "InvalidPage"
)

var (
	_PageType_index_0 = [...]uint8{0, 17, 29, 41, 51, 58, 73, 86, 103, 118, 135, 144, 157, 172}
	_PageType_index_1 = [...]uint8{0, 11}
)

func (i PageType) String() string {
	switch {
	case 0 <= i && i <= 12:
		return _PageType_name_0[_PageType_index_0[i]:_PageType_index_0[i+1]]
	case i == 255:
		return _PageType_name_1
	default:
		return fmt.Sprintf("PageType(%d)", i)
	}
}
