// Code generated by "stringer -type PageType"; DO NOT EDIT

package dexcom

import "fmt"

const (
	_PageType_name_0 = "MANUFACTURING_DATAFIRMWARE_PARAMETER_DATAPC_SOFTWARE_PARAMETERSENSOR_DATAEGV_DATACAL_SETDEVIATIONINSERTION_TIMERECEIVER_LOG_DATARECEIVER_ERROR_DATAMETER_DATAUSER_EVENT_DATAUSER_SETTING_DATA"
	_PageType_name_1 = "INVALID_PAGE"
)

var (
	_PageType_index_0 = [...]uint8{0, 18, 41, 62, 73, 81, 88, 97, 111, 128, 147, 157, 172, 189}
	_PageType_index_1 = [...]uint8{0, 12}
)

func (i PageType) String() string {
	switch {
	case 0 <= i && i <= 12:
		return _PageType_name_0[_PageType_index_0[i]:_PageType_index_0[i+1]]
	case i == 255:
		return _PageType_name_1
	default:
		return fmt.Sprintf("PageType(%d)", i)
	}
}
