// Code generated by "stringer -type SensorChange"; DO NOT EDIT

package dexcom

import "fmt"

const (
	_SensorChange_name_0 = "Stopped"
	_SensorChange_name_1 = "Started"
)

var (
	_SensorChange_index_0 = [...]uint8{0, 7}
	_SensorChange_index_1 = [...]uint8{0, 7}
)

func (i SensorChange) String() string {
	switch {
	case i == 1:
		return _SensorChange_name_0
	case i == 7:
		return _SensorChange_name_1
	default:
		return fmt.Sprintf("SensorChange(%d)", i)
	}
}
