// Code generated by "stringer -type Trend"; DO NOT EDIT

package dexcom

import "fmt"

const _Trend_name = "UP_UPUPUP_45FLATDOWN_45DOWNDOWN_DOWNNOT_COMPUTABLEOUT_OF_RANGE"

var _Trend_index = [...]uint8{0, 5, 7, 12, 16, 23, 27, 36, 50, 62}

func (i Trend) String() string {
	i -= 1
	if i >= Trend(len(_Trend_index)-1) {
		return fmt.Sprintf("Trend(%d)", i+1)
	}
	return _Trend_name[_Trend_index[i]:_Trend_index[i+1]]
}
